### ISSUE TITLE
Zoom out while animation runs

### ISSUE THREAD

**Issue by PhilipW97** [MarcMogdanz/marcmogdanz.de#17]
When the user zooms out while the slide-in animation for the Projects run the pages width gets wider than its content. 
![IMG_18960B24B3B2-1](https://user-images.githubusercontent.com/44462043/72682831-ad66e900-3ad1-11ea-8501-5690a08ecbc8.jpeg)

**Comment by MarcMogdanz** [comment]
As I don't have a fucking clue what weird black css magic is responsible for this, I hope it will be fixed when I work on #20

**Comment by MarcMogdanz** [comment]
Closed via #35
